qq:
  host: "ssl://smtp.qq.com:465"
  user: "lantai171892716@foxmail.com"
  password: "tcpqthckocgdbjfb"

wangyi:
  host: "ssl://smtp.163.com:465"
  user: "lantai171892716@163.com"
  password: "UZjcSi9ZuB7GGGaP"

test:
  host: "http://www.baidu.com"
  user: "root"
  password: "123456789"